package com.queuemanagementsystem.model;
/**
 * Representa un administrador responsable de la configuración y gestión del sistema.
 * Extiende la clase base User.
 */
public class Administrator extends User {
    private int accessLevel;

    /**
     * Constructor por defecto
     */
    public Administrator() {
        super();
        this.accessLevel = 1; // Nivel de acceso por defecto
    }

    /**
     * Constructor parametrizado con campos de usuario base
     *
     * @param id Identificador único del administrador
     * @param name Nombre completo del administrador
     * @param password Contraseña de autenticación del administrador
     */
    public Administrator(String id, String name, String password) {
        super(id, name, password);
        this.accessLevel = 1; // Nivel de acceso por defecto
    }

    /**
     * Constructor completo con todos los campos
     *
     * @param id Identificador único del administrador
     * @param name Nombre completo del administrador
     * @param password Contraseña de autenticación del administrador
     * @param accessLevel Nivel de permisos del administrador
     */
    public Administrator(String id, String name, String password, int accessLevel) {
        super(id, name, password);
        this.accessLevel = accessLevel;
    }

    /**
     * Configura una categoría de servicio
     *
     * @param category La categoría a configurar
     * @return true si la categoría fue configurada exitosamente, false en caso contrario
     */
    public boolean configureCategory(Category category) {
        // Esto normalmente involucraría lógica de validación y persistencia
        // Por ahora, asumiremos que la categoría es válida si tiene un nombre y un prefijo
        return category != null && category.getName() != null &&
                !category.getName().isEmpty() && category.getPrefix() != null &&
                !category.getPrefix().isEmpty();
    }

    /**
     * Crea una nueva estación de servicio
     *
     * @param station La estación a crear
     * @return true si la estación fue creada exitosamente, false en caso contrario
     */
    public boolean createStation(Station station) {
        // Esto normalmente involucraría lógica de validación y persistencia
        return station != null && station.getNumber() > 0;
    }

    /**
     * Elimina una estación de servicio
     *
     * @param station La estación a eliminar
     * @return true si la estación fue eliminada exitosamente, false en caso contrario
     */
    public boolean removeStation(Station station) {
        // Esto normalmente involucraría lógica de validación y persistencia
        return station != null;
    }

    /**
     * Monitorea estadísticas de servicio
     *
     * @return Un string con la información actual de estadísticas
     */
    public String superviseStatistics() {
        // Esto normalmente consultaría el servicio de estadísticas
        return "Statistics monitoring functionality accessed by administrator: " + getName();
    }

    /**
     * Genera un informe de productividad
     *
     * @param reportType El tipo de informe a generar (ej. "DAILY", "WEEKLY")
     * @return Un string que contiene el informe de productividad
     */
    public String generateProductivityReport(String reportType) {
        // Esto normalmente consultaría el servicio de estadísticas para datos específicos del informe
        StringBuilder report = new StringBuilder();
        report.append("=== ").append(reportType).append(" PRODUCTIVITY REPORT ===\n");
        report.append("Generated by: ").append(getName()).append("\n");
        report.append("Date: ").append(java.time.LocalDate.now()).append("\n");
        report.append("This is a placeholder for the actual report content");

        return report.toString();
    }

    // Getters y Setters

    public int getAccessLevel() {
        return accessLevel;
    }

    public void setAccessLevel(int accessLevel) {
        this.accessLevel = accessLevel;
    }

    /**
     * Devuelve una representación en string de este Administrador
     *
     * @return Una representación en string
     */
    @Override
    public String toString() {
        return "Administrator{" +
                "id='" + getId() + '\'' +
                ", name='" + getName() + '\'' +
                ", accessLevel=" + accessLevel +
                '}';
    }
}